name: phpunit
on: push
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
      - name: Composer Install
        if: steps.composer_cache.outputs.cache-hit != 'true'
        run: |
          composer install -n --prefer-dist
      - name: Run PHPUnit
        run: |
          ./vendor/bin/phpunit --stop-on-failure ./tests/
